server:
  port: 13000
spring:
  application:
    name: server-config-client
  rabbitmq:
    host: 39.105.184.130
    port: 5672
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: refresh
       
info:
  profile: dev-server-3
